@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
UniquePersonList -right-> Person

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Price
Person *--> PropertyType
Person *--> Intention

' Keep visual order neat
Address -[hidden]right-> Price
Price -[hidden]right-> PropertyType
PropertyType -[hidden]right-> Intention
@enduml
